site_name: قاموس أسس التقني
site_url: https://dictionary.aosus.org
site_author: مجتمع أسس
repo_name: aosus/arabic-tech-dictionary
repo_url: https://github.com/aosus/arabic-tech-dictionary
copyright: GFDLv1.2

plugins:
  - autolinks
  - search # necessary for search to work
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
  language: ar
  font: false
  logo: https://aosus.org/uploads/default/original/2X/c/cb764c17cb5bfd2e2874b7ab58e323e59f8510fc.png
  favicon: https://aosus.org/uploads/default/original/2X/d/d3a14401f62f830b2b222342a3b215dbf1b94fc1.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: teal
    accent: blue

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aosus
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aosusorg
    - icon: fontawesome/brands/telegram
      link: https://t.me/aosus
    - icon: matrix
      link: https://matrix.to/#/#aosus:tchncs.de

extra_css:
  - extra/extra.css

nav:
    - الرئيسية: 'index.md'
    - القاموس: 'dictionary.md'
    - 'مجتمع أسس': 'https://aosus.org'
    - 'تيليجرام': 'https://t.me/aosus'
    - 'ماتركس': 'https://matrix.to/#/#aosus:tchncs.de'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: true

